### PR TITLE
Feature/two talons

### PR DESCRIPTION
**Pull request by edf42001**

### CODE REVIEW

**Review by redbow-kimee — COMMENTED** [review]
Where did the auto files go??

**Review by redbow-kimee — COMMENTED** [review]
File Creator -- Make its own branch

**Review by redbow-kimee — COMMENTED** [review]
why did drive controller change on a branch that is supposed to be for the *Elavator*

**Comment by edf42001** [comment]
Probably when feature/drive was merged into it, if not it's because something moved, it's probably inconsequential, I suggest using diff viewer

**Comment by RedBow** [comment]
rejected, but a subset may have been included in the cherry picking merge onto integration.

**Pull request closed without merging**
