### PR TITLE
Seneca code -> dev

### PR DESCRIPTION
**Pull request by edf42001**

### CODE REVIEW

**Comment by edf42001** [comment]
Now it's MAR Champs Code -> dev

**Review by redbow-kimee — COMMENTED** [review]
Dashboard Main:
    -Battery Number is disabled
    -position and not pure pursuit disabled
    -our switch, opponent switch, scale disabled (I think these are unnecessary anyways)
    -red == blue should always be false?? why are we making this comparison?
    -can we clean up some of the lines?
Autonomous and Auto Routine Selector and 2CubeSelector:
    -Instead of converting LRL to bools and then using the bools, you could to string case statements which may be more readable, and perform fewer redundant operations.
    -How are we reading position and not pure pursuit, my understanding is they are disabled in dashboard?? auto population?? why aren't other fields auto populated
Run Auto File:
    -Elavator stop at end is disabled?
Drive/CheesyDrive
    -please clean up the backwards wires.
    -please add comments about what each section of the code is doing.
    -consider simplest form of some of the bool logic
Drive/PixyGetData:
    -there are unused byte joins.
    -it looks to me like we are reading more data from the I2C bus than necessary, I2C read is a blocking operation which waits for each byte, so minimize the data read
Drive/Commands:
    -there are some clusters covering some wires and VIs.
    -Turn for Angle: the endAngle output is a calculated angle, not necessarily the actual angle, that may be a desired behavior, however this should be noted.
Drive/Implementation/Drive Controller:
    -Overlapping wires/constants in device setup, and some of the framework wires are behind the modes loop. Next year I would like to put each mode in a function
    -clean up the wires like everywhere
*location loop
    -stop it with the backwards/messsyyy wires.
    -NT Position? is this being auto populated in dashboard
*drive to cube:
    -backwards wires, and please clean some of the messy ones up.
    -unused comparisons
Drive/PurePursuit
    -Very Messy
    -Hard to understand documentation
    -consider how to simplify some of the boolean logic
Elavator/Implementation/Elevator Controller
    -Little Bit Messy.
    -go to height: unused calculations.
    -height calculation loop: messy and backwards wires.
Robot Global Data:
    -Not pure Pursuit may be unused,
    -also the routine is from old auto selectors.
    -clean unused data items
Intake/Implementation/Intake Controller
    -Has cube is never logged
Robot Main:
    -NavX should go in periodic tasks or subsystems.
Subsystems:
    -Climber can be its own subsystem, in Periodic Tasks, a VI with a loop, wtf?
Teleop:
    -clean up wires
    -consider how to make some of the boolean logic cleaner 
Logging/Create file:
    -it is possible to get match type (quals/elims/practice), if you want that in name too. also if it is a replay.
Logging/Headers:
    -Alliance you can format to red/blue string 
    -Match Type can be formatted to practice/quals/elims string
    -Headers say elevator where it should say climber
    -DriveMode/Slow Mode boolean with a lowercase b please
    -Driver Operation has type float where it should have string
    -Top Limit should has type String, should have type bool
    -Height should have type float
    -Pixy X should have type int
    -Distance should have type Float
    -Extra float type
    -I think there's an extra float after the PDPs.
    -Missing has cube data
Logging/Data:
    -Clean up the wires, this is the primary source of inconsistencies in our logs.
    -Missing Has Cube data

**Comment by redbow-kimee** [comment]
Review made against 045c378

**Comment by redbow-kimee** [comment]
Commentary on the robot project
AutoRoutineSelector.vi and Autonomous.vi
--LRL code to boolean just to go back to String. why not take the substring that you are using and put that into AutoRoutineSelector.
Robot Main:
-- NavX should go in subsystems.vi or periodic tasks.vi
Teleop:
-- Intake: PDP reading can go inside of state machine. better readability.
-- Clean up wires.
SubSystems:
-- does it make sense to have climber in subsystems or in periodic
Periodic/logging:
 -- not that we ever use test mode, but if we did , it would not get logged
 -- Why does there need to be feedback on the stop condition of the wait to enable loop. and why is there a case statement around logging. (even if there is a good reason, it is not apparent from the code)
 -- LoggingData.vi: please clean up wires. 
    -- check slow mode type (is int, says booelan)
    -- looks like theres an extra float after Voltage and before drive operation. it throws the type array off.

    
Drive/CheesyDrive: needs wire cleanups.
Drive/purepursuit: needs cleanup and needs better in-code documentation
Drive/drivecontroller: needs cleanup and better in-code documentation
Elevator/ElevatorController: nees wire clean up (Especially around talon setup, and sensor reading). and also a bit of in-code documentation. 
Intake/IntakeController: wire clean up. documentation about the sonar read loop.

**Comment by redbow-kimee** [comment]
Dashboard, and FileCreater/PathDrawer just generally need documentation and wire clean up

**Review by redbow-kimee — CHANGES_REQUESTED** [review]
see previous two comments

**Review by redbow-kimee — APPROVED** [review]

**Comment by redbow-kimee** [comment]
Its not quite perfect, but a lot better than it was

**Pull request merged**
