### PR TITLE
Feature/drive

### PR DESCRIPTION
**Pull request by edf42001**

### CODE REVIEW

**Review by redbow-kimee — COMMENTED** [review]
why are there elavator changes???? Not applicable to the Drive

**Review by redbow-kimee — COMMENTED** [review]
who changed elavator command helper? this is from WPI

**Review by redbow-kimee — COMMENTED** [review]
Why is intake on here? Not applicable to the drive

**Review by redbow-kimee — COMMENTED** [review]
WHO CHANGED ROBOT MAIN

**Review by redbow-kimee — COMMENTED** [review]
File creator should be its own review.

**Comment by edf42001** [comment]
Because dev was merged in

**Comment by edf42001** [comment]
Niko, he cosmetically changed a cluster

**Comment by edf42001** [comment]
Same reason. Also the branch is more of an "auto" branch now, they couldn't program atuo without elevator or intake commands

**Comment by edf42001** [comment]
Don't know, I suggest using the diff tool to see if it was anything important. Though the navX Main VI does need to be moved out of it and into Drive Controller

**Comment by edf42001** [comment]
Fiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiine

**Comment by RedBow** [comment]
Cherry picking merge was accomplished onto integration

**Pull request closed without merging**
