### PR TITLE
Feature/integrate pure pursuit

### PR DESCRIPTION
**Pull request by edf42001**

### CODE REVIEW

**Comment by edf42001** [comment]
1) We fixed the broken elevator controller. 
2) Lets do branch deleting in a controlled manner later. A couple of them are still needed

**Review by redbow-kimee — CHANGES_REQUESTED** [review]
Code review KM:
ROBOT:
Teleop.vi
    are we sure we want cheesy drive to be the default drive?
Autonomous.vi
    unused NT reads
	where does data get into global data
Test.vi
	the loop that reports the robot mode should not be disabled
support code/One shot pulse and buttons pressed
	the use of greater than with booleans is rather unclear. consider using input AND (input XOR feedback) or equivelant
support code/ArcadeJoystick
	Is this from WPI? why is it here and not in dependencies
support code/calculatefilepath and debuggingglobals and handledeadband
	unused vi
drive/purepursuit/adjustleftrightspeeds
	is there a right left pair for it?
	unused
drive/purepursuit/closest point
	the backwards wires make it difficult to understand
drive/purepursuit/endofpathhandler
	unused inputs/outputs
	looks very incomplete
drive/purepursuit/injectpoints
	what is this supposed to do?
drive/purepursuit/lookaheadpoint
	stop with the backwards lines
drive/purepursuit/purepursuit
	why is it in a loop if it immediately stops
	backwards wires make it hard to read.
drive/purepursuit/purepursuittester
	broken wires
	unused vi
drive/purepursuit/radiusofcirclethreepoints
	in the IEEE spec for floating points (http://ieeexplore.ieee.org/document/4610935/) NaN indicates an illegal operation such as divide by zero (which, on a case-by-case basis can indicate infinity) there are constants to indicate + and - infinity
drive/purepursuit/testpurepursuit
	unused vi
Drive/implementation/drive controller
	unwired case outputs in read current (how is it executable)
Drive/commands/drive for time
	unwired output indicator
Drive/commands/all
	theres a lot of places where there are large clusters covering other ones.
elevator/implementation/elevator controller
	both talons have the same name
	not all outputs on the case statement are wired
elevator/commands/all
	there's duplicated code to transform the setpoints.
Robot Main
	the navx thing can go in subsystems, the drive controller or periodic tasks. but it is sub optimal in main.
Subsystems
	vision is disabled (is this intentional?)

DASHBOARD:
dashboard main.vi
    I think that some of the NT writes are duplicates of some automatic NT write thing (https://www.chiefdelphi.com/forums/showthread.php?t=162863)

SHARED:
go position.vi and hold position.vi
	what does this do? it looks empty
	do we need it?

SUPPORT/PATH DRAWER:
distance formula.vi, inject points.vi, smoother.vi
	this code is also on the robot. why not put it once in shared
path drawer main.vi
	whats with all the unused controls?

SUPPORT/FILE CREATOR:
filecreatormain.vi
	unused controls?
files
	not all the files look complete. all of them need a regular version (with elevator/intake), purepursuit version (with elevator/intake)

**Comment by RedBow** [comment]
there's a lot of comments and concerns in my review, but there's a lot of code in there, and a lot of it is very good code.

**Comment by edf42001** [comment]
image

**Comment by edf42001** [comment]
Also I have no clue why it's an image

**Comment by RedBow** [comment]
If you right click a VI in the project explorer, there's an option "find->callers"

**Comment by RedBow** [comment]
Do we want to stick with them in globals and maybe have a loop in Periodic that updates the NT in globals? Or can we get it to a reliable state without globals.

**Comment by RedBow** [comment]
There's literally a button to clean up your wires for you. So that shouldn't be an issue.

**Comment by RedBow** [comment]
If it's incomplete, do some cleaning and also leave a TODO comment stating what needs to be done.

**Comment by edf42001** [comment]
I'm confident we can get the dashboard working. 
Is that a different button from the one that cleans up the entire block diagram? If it is, it also moves objects around restructuring how you visualize the data flow in your mind, which makes a programmer use it sparingly. 
Can that be done after build season?

**Comment by RedBow** [comment]
Cool. 

If you select a bunch of wires or a case statement or something like that it will only apply it to those items.

It is already after build season.

**Pull request closed without merging**
